name: gh-secret-file
on: [push]
jobs:
  get-the-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: "curl -H 'Authorization: token ${{ secrets.GITHUB_TSECRET_GITHUB_TOKENOKEN }}'  -H 'Accept: application/vnd.github.v4.raw' -O -L https://api.github.com/repos/jhasselbring/secrets/contents/se/be/secret.json"
