on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  brp:
    name: Build Release Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use nodejs v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Download service-account.json
        run: "curl -H 'Authorization: token ${{ secrets.SECRET_GITHUB_TOKEN }}'  -H 'Accept: application/vnd.github.v4.raw' -O -L https://api.github.com/repos/jhasselbring/secrets/contents/commander-endpoint/service-account.json"
      - name: Download & install pkg
        run: npm install pkg -g
      - name: Build artifacts
        run: npm run build
      - run: ls
      - run: ls build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Commander-linux
        id: upload-release-linux-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./build/Commander-linux
          asset_name: Commander-linux
          asset_content_type: application/x-binary
      - name: Upload Commander-win.exe
        id: upload-release-windows-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./build/Commander-win.exe
          asset_name: Commander-win.exe
          asset_content_type: application/x-binary